// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKdcdRzjrV53_XxzByYH03F-NyXmK2OEA',
    appId: '1:640657859213:web:966a6e95d8200646d1f8c4',
    messagingSenderId: '640657859213',
    projectId: 'totem-61421',
    authDomain: 'totem-61421.firebaseapp.com',
    storageBucket: 'totem-61421.firebasestorage.app',
    measurementId: 'G-SKG1QJ3QPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpwElmjSShsJi9cI69LltBDqNIi3zGLrM',
    appId: '1:640657859213:android:06369299c9f42e8dd1f8c4',
    messagingSenderId: '640657859213',
    projectId: 'totem-61421',
    storageBucket: 'totem-61421.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOOodWSWO6Af89E5ukE_J9s5m66u8Iy2E',
    appId: '1:640657859213:ios:c399aa02de596d69d1f8c4',
    messagingSenderId: '640657859213',
    projectId: 'totem-61421',
    storageBucket: 'totem-61421.firebasestorage.app',
    iosBundleId: 'com.example.totem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOOodWSWO6Af89E5ukE_J9s5m66u8Iy2E',
    appId: '1:640657859213:ios:c399aa02de596d69d1f8c4',
    messagingSenderId: '640657859213',
    projectId: 'totem-61421',
    storageBucket: 'totem-61421.firebasestorage.app',
    iosBundleId: 'com.example.totem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKdcdRzjrV53_XxzByYH03F-NyXmK2OEA',
    appId: '1:640657859213:web:fee152687db2b70bd1f8c4',
    messagingSenderId: '640657859213',
    projectId: 'totem-61421',
    authDomain: 'totem-61421.firebaseapp.com',
    storageBucket: 'totem-61421.firebasestorage.app',
    measurementId: 'G-K8THK7EDSF',
  );
}
